services:
  postgres:
    image: 'postgres:16'
    container_name: logistisen_db_container
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - 'POSTGRES_DB=logistisen_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
